version: '3.4'

services:
  sampleblog:
    image: sampleblog
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mysite:/app/mysite
    command: "python /app/mysite/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
