version: '3.8'
services:
  backend:
    build: 
      context: mysite
      dockerfile: Dockerfile
    volumes:
      - /mysite:/app/mysite
    ports:
      - 8000:8000
    command: "python manage.py runserver"